version: '3'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Allow empty password for MySQL root user
      - MYSQL_DATABASE=firstsql
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./Main.js:/app/Main.js  # Mount Main.js into the container

  db:
    image: mysql:latest
    ports:
      - "3300:3306"  # Map Docker's internal port 3306 to port 3307 on the host
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty password for MySQL root user
      MYSQL_DATABASE: firstsql
